# Generated by Django 3.2 on 2021-11-27 03:16

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='label'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('label', 'parent')},
        ),
    ]
