# Generated by Django 3.2 on 2021-11-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
