# Generated by Django 3.2 on 2021-11-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_category_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
