# Generated by Django 3.2 on 2021-11-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_alter_category_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('label', 'parent')},
        ),
    ]
