version: "3.9"

services:
  core:
    build: .
    hostname: ${core_host_name:-core}
    container_name: core
    tty: true
    environment:
      - TERM=xterm-256color
    volumes:

      - type: bind
        source: .
        target: /home/appuser/src
