# Generated by Django 3.2 on 2021-12-03 02:46

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image'),
        ),
    ]
